title: 클린고파스
author:
  name: koreapasnoad
  email: koreapasnoad@gmail.com
description: 고파스 광고 차단 방법을 알려주는 블로그입니다. 크롬 ublock origin 플러그인이나 Brave 브라우저 또는
  유니콘 프로 광고차단앱이 필요합니다. 광고없는 클린한 고파스 하세요!
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: classic
